# Generated by Django 3.1.14 on 2023-05-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeaddressinfo',
            name='union',
        ),
        migrations.RemoveField(
            model_name='employeeaddressinfo',
            name='upazilla',
        ),
        migrations.RemoveField(
            model_name='employeejobinfo',
            name='first_time_scale_due_year',
        ),
        migrations.RemoveField(
            model_name='employeejobinfo',
            name='recreation_leave_due_year',
        ),
        migrations.RemoveField(
            model_name='employeejobinfo',
            name='second_time_scale_due_year',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='driving_license_passport',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='e_tin',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='nid',
        ),
    ]
