# Generated by Django 3.1.14 on 2023-05-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20230525_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaddressinfo',
            name='union',
        ),
        migrations.RemoveField(
            model_name='studentaddressinfo',
            name='upazilla',
        ),
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=574551, unique=True),
        ),
    ]
