# Generated by Django 3.1.14 on 2023-05-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20230528_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=520010, unique=True),
        ),
    ]
